library(ggplot2)
library(plyr)
library(reshape2)

#Préparation données + temps global machine
data_seq <- data.frame(read.csv2(file="tri_seq.csv", sep=';', dec='.', header=TRUE))
data_thread2 <- data.frame(read.csv2(file="~/Documents/tp_performance/tris2.csv", sep=';', dec='.', header=TRUE))
data_thread3 <- data.frame(read.csv2(file="~/Documents/tp_performance/tris3.csv", sep=';', dec='.', header=TRUE))
data_thread4 <- data.frame(read.csv2(file="~/Documents/tp_performance/tris4.csv", sep=';', dec='.', header=TRUE))
data_thread5 <- data.frame(read.csv2(file="~/Documents/tp_performance/tris5.csv", sep=';', dec='.', header=TRUE))
data_thread6 <- data.frame(read.csv2(file="~/Documents/tp_performance/tris6.csv", sep=';', dec='.', header=TRUE))
data_thread7 <- data.frame(read.csv2(file="~/Documents/tp_performance/tris7.csv", sep=';', dec='.', header=TRUE))
data_thread8 <- data.frame(read.csv2(file="~/Documents/tp_performance/tris8.csv", sep=';', dec='.', header=TRUE))
data_thread9 <- data.frame(read.csv2(file="~/Documents/tp_performance/tris9.csv", sep=';', dec='.', header=TRUE))
data_thread10 <- data.frame(read.csv2(file="~/Documents/tp_performance/tris10.csv", sep=';', dec='.', header=TRUE))
data_thread11 <- data.frame(read.csv2(file="~/Documents/tp_performance/tris11.csv", sep=';', dec='.', header=TRUE))
data_thread12 <- data.frame(read.csv2(file="~/Documents/tp_performance/tris12.csv", sep=';', dec='.', header=TRUE))
data_thread13 <- data.frame(read.csv2(file="~/Documents/tp_performance/tris13.csv", sep=';', dec='.', header=TRUE))
data_thread14 <- data.frame(read.csv2(file="~/Documents/tp_performance/tris14.csv", sep=';', dec='.', header=TRUE))
data_thread15 <- data.frame(read.csv2(file="~/Documents/tp_performance/tris15.csv", sep=';', dec='.', header=TRUE))
data_thread16 <- data.frame(read.csv2(file="~/Documents/tp_performance/tris16.csv", sep=';', dec='.', header=TRUE))

stat_naif<-ddply(data_seq,c("taille"),summarise,N=length(tempsMachine),mean=mean(tempsMachine),sd=sd(tempsMachine),se=1.96*(sd/sqrt(N)))
stat_naif2<-ddply(data_thread2,c("taille"),summarise,N=length(tempsMachine),mean=mean(tempsMachine),sd=sd(tempsMachine),se=1.96*(sd/sqrt(N)))
stat_naif3<-ddply(data_thread3,c("taille"),summarise,N=length(tempsMachine),mean=mean(tempsMachine),sd=sd(tempsMachine),se=1.96*(sd/sqrt(N)))
stat_naif4<-ddply(data_thread4,c("taille"),summarise,N=length(tempsMachine),mean=mean(tempsMachine),sd=sd(tempsMachine),se=1.96*(sd/sqrt(N)))
stat_naif5<-ddply(data_thread5,c("taille"),summarise,N=length(tempsMachine),mean=mean(tempsMachine),sd=sd(tempsMachine),se=1.96*(sd/sqrt(N)))
stat_naif6<-ddply(data_thread6,c("taille"),summarise,N=length(tempsMachine),mean=mean(tempsMachine),sd=sd(tempsMachine),se=1.96*(sd/sqrt(N)))
stat_naif7<-ddply(data_thread7,c("taille"),summarise,N=length(tempsMachine),mean=mean(tempsMachine),sd=sd(tempsMachine),se=1.96*(sd/sqrt(N)))
stat_naif8<-ddply(data_thread8,c("taille"),summarise,N=length(tempsMachine),mean=mean(tempsMachine),sd=sd(tempsMachine),se=1.96*(sd/sqrt(N)))
stat_naif9<-ddply(data_thread9,c("taille"),summarise,N=length(tempsMachine),mean=mean(tempsMachine),sd=sd(tempsMachine),se=1.96*(sd/sqrt(N)))
stat_naif10<-ddply(data_thread10,c("taille"),summarise,N=length(tempsMachine),mean=mean(tempsMachine),sd=sd(tempsMachine),se=1.96*(sd/sqrt(N)))
stat_naif11<-ddply(data_thread11,c("taille"),summarise,N=length(tempsMachine),mean=mean(tempsMachine),sd=sd(tempsMachine),se=1.96*(sd/sqrt(N)))
stat_naif12<-ddply(data_thread12,c("taille"),summarise,N=length(tempsMachine),mean=mean(tempsMachine),sd=sd(tempsMachine),se=1.96*(sd/sqrt(N)))
stat_naif13<-ddply(data_thread13,c("taille"),summarise,N=length(tempsMachine),mean=mean(tempsMachine),sd=sd(tempsMachine),se=1.96*(sd/sqrt(N)))
stat_naif14<-ddply(data_thread14,c("taille"),summarise,N=length(tempsMachine),mean=mean(tempsMachine),sd=sd(tempsMachine),se=1.96*(sd/sqrt(N)))
stat_naif15<-ddply(data_thread15,c("taille"),summarise,N=length(tempsMachine),mean=mean(tempsMachine),sd=sd(tempsMachine),se=1.96*(sd/sqrt(N)))
stat_naif16<-ddply(data_thread16,c("taille"),summarise,N=length(tempsMachine),mean=mean(tempsMachine),sd=sd(tempsMachine),se=1.96*(sd/sqrt(N)))
p <- ggplot()


p <- p + geom_point(data=stat_naif, aes(x=taille, y=mean, colour = "algorithme naïf"))
p <- p + geom_line(data=stat_naif, aes(x=taille, y=mean, colour = "algorithme naïf"))
p <- p + geom_point(data=stat_naif2, aes(x=taille, y=mean, colour = "algorithme avec 2 threads"))
p <- p + geom_line(data=stat_naif2, aes(x=taille, y=mean, colour = "algorithme avec 2 threads"))
p <- p + geom_point(data=stat_naif3, aes(x=taille, y=mean, colour = "algorithme avec 3 threads"))
p <- p + geom_line(data=stat_naif3, aes(x=taille, y=mean, colour = "algorithme avec 3 threads"))
p <- p + geom_point(data=stat_naif4, aes(x=taille, y=mean, colour = "algorithme avec 4 threads"))
p <- p + geom_line(data=stat_naif4, aes(x=taille, y=mean, colour = "algorithme avec 4 threads"))
p <- p + geom_point(data=stat_naif5, aes(x=taille, y=mean, colour = "algorithme avec 5 threads"))
p <- p + geom_line(data=stat_naif5, aes(x=taille, y=mean, colour = "algorithme avec 5 threads"))
p <- p + geom_point(data=stat_naif6, aes(x=taille, y=mean, colour = "algorithme avec 6 threads"))
p <- p + geom_line(data=stat_naif6, aes(x=taille, y=mean, colour = "algorithme avec 6 threads"))
p <- p + geom_point(data=stat_naif7, aes(x=taille, y=mean, colour = "algorithme avec 7 threads"))
p <- p + geom_line(data=stat_naif7, aes(x=taille, y=mean, colour = "algorithme avec 7 threads"))
p <- p + geom_point(data=stat_naif8, aes(x=taille, y=mean, colour = "algorithme avec 8 threads"))
p <- p + geom_line(data=stat_naif8, aes(x=taille, y=mean, colour = "algorithme avec 8 threads"))
p <- p + geom_point(data=stat_naif9, aes(x=taille, y=mean, colour = "algorithme avec 9 threads"))
p <- p + geom_line(data=stat_naif9, aes(x=taille, y=mean, colour = "algorithme avec 9 threads"))
p <- p + geom_point(data=stat_naif10, aes(x=taille, y=mean, colour = "algorithme avec 10 threads"))
p <- p + geom_line(data=stat_naif10, aes(x=taille, y=mean, colour = "algorithme avec 10 threads"))
p <- p + geom_point(data=stat_naif11, aes(x=taille, y=mean, colour = "algorithme avec 11 threads"))
p <- p + geom_line(data=stat_naif11, aes(x=taille, y=mean, colour = "algorithme avec 11 threads"))
p <- p + geom_point(data=stat_naif12, aes(x=taille, y=mean, colour = "algorithme avec 12 threads"))
p <- p + geom_line(data=stat_naif12, aes(x=taille, y=mean, colour = "algorithme avec 12 threads"))
p <- p + geom_point(data=stat_naif13, aes(x=taille, y=mean, colour = "algorithme avec 13 threads"))
p <- p + geom_line(data=stat_naif13, aes(x=taille, y=mean, colour = "algorithme avec 13 threads"))
p <- p + geom_point(data=stat_naif14, aes(x=taille, y=mean, colour = "algorithme avec 14 threads"))
p <- p + geom_line(data=stat_naif14, aes(x=taille, y=mean, colour = "algorithme avec 14 threads"))
p <- p + geom_point(data=stat_naif15, aes(x=taille, y=mean, colour = "algorithme avec 15 threads"))
p <- p + geom_line(data=stat_naif15, aes(x=taille, y=mean, colour = "algorithme avec 15 threads"))
p <- p + geom_point(data=stat_naif16, aes(x=taille, y=mean, colour = "algorithme avec 16 threads"))
p <- p + geom_line(data=stat_naif16, aes(x=taille, y=mean, colour = "algorithme avec 16 threads"))

ggsave(filename="global_temps_machine.png", plot=p, width=20, height=20)

#Efficacité 2 threads
accel<-ddply(stat_naif,c("taille"), , accelration=stat_naif$mean/stat_naif2$mean)
eff <- ddply(accel,c("taille"), x+14, eff=accel$acceleration/16)
print(stat_naif)
print(accel)
print(eff)
